### ISSUE TITLE
Set up Project Structure for R package

### ISSUE THREAD

**Issue by harryyikhchan** [UBC-MDS/snapedautilityR#2]

**Comment by AraiYuno** [comment]
@harryyikhchan  @dol23asuka  
Why don't we include Usage section based on the examples that exist in the function specifications?

**Comment by AraiYuno** [comment]
Added a sample usage section. let me know if this looks good.
@harryyikhchan  @dol23asuka 
![image](https://user-images.githubusercontent.com/28745975/150460592-85c329df-f83e-4b1c-9772-489b3230c18f.png)

**Comment by dol23asuka** [comment]
Looks good to me

**Comment by harryyikhchan** [comment]
Yes, pls merge the PR.
