### ISSUE TITLE
Write test cases and code for function plot_histograms

### ISSUE THREAD

**Issue by harryyikhchan** [UBC-MDS/snapedautilityR#9]

**Comment by dol23asuka** [comment]
<img width="685" alt="Screen Shot 2022-01-28 at 2 09 32 AM" src="https://user-images.githubusercontent.com/89939117/151528362-8cfd9c69-56dc-473c-a381-70f0c36757c9.png">
See some similar wanrings here. Is it a big deal? (seems like not tho)

**Comment by AraiYuno** [comment]
@dol23asuka Thanks!
I have added suppressWarnings. These warnings are not part of the unit tests, but part of the ggplot2's warnings when some data points are excluded due to them being extreme outliers. 
https://github.com/UBC-MDS/snapedautilityR/pull/16

Check out the pull request above

**Comment by dol23asuka** [comment]
Make sense!
